server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ #change this to your database url
    password: stevo1820 #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
